machine:
  ruby:
    version: 2.3.0

test:
  override:
    - bundle exec rspec -r rspec_junit_formatter --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/junit.xml --format documentation
  post:
    - bundle exec rubocop -RDES
    - bundle exec rake eslint:run
